# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###
# Send a body with a JSON object
POST http://127.0.0.1:8000/recomendation
Content-Type: application/json

{
  "newsId": "61e07f64-cddf-46f2-b50c-ea0a39c22050",
  "userId": "2c1080975e257ed630e26679edbe4d5c850c65f3e09f655798b0bba9b42f2110"
}


### 